# Generated by Django 4.2.1 on 2023-06-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_notes', '0005_rename_usuario_usuario_username_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='app_notes.usuario'),
        ),
    ]
